//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOSIIX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IDUsuarios { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string Email { get; set; }
        public Nullable<int> Celular { get; set; }
    }
}
